TRUNCATE edges, activity_log, nodes RESTART IDENTITY CASCADE;

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000001', 'hunch', 'Civilizational Optionality as Core Scarcity', 'From Indy Johar substack on what civilization protects.', 'promoted', 4, 'early_evidence', ARRAY['capital_strategy', 'formation'], '{"title":"Civilizational Optionality as Core Scarcity","summary":"The scarce resource in cascading social-biophysical crises is not money or technology but optionality: the structural ability of societies to still choose between multiple futures.","structured_claim":{"if":"social-biophysical whirlpools intensify without intervention","then":"societies lose the structural ability to choose between futures","because":"volatility and inequality compound into irreversible pathway lock-in"},"assumption_type":"foreground","entities":[{"name":"Civilization Options Fund","type":"organisation"},{"name":"optionality","type":"concept"}],"domain_tags":["capital_strategy","formation"],"open_questions":["How do we measure remaining optionality in a system?","At what point does option loss become irreversible?"],"confidence_assessment":{"level":4,"basis":"early_evidence"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '6 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000002', 'hunch', 'Helical Organising Over Linear Project Management', 'From The Geometries of Change.', 'promoted', 3, 'analogy', ARRAY['formation', 'demand_architecture'], '{"title":"Helical Organising Over Linear Project Management","summary":"Linear project management assumes a fixed destination, but wicked problems mutate as we intervene. Helical organising governs curvature rather than speed and preserves reachable optionality.","structured_claim":{"if":"organisations adopt helical organising instead of linear project management","then":"they preserve reachable optionality and increase adaptive capacity","because":"helical structures govern curvature not speed and delay irreversibility"},"assumption_type":"foreground","entities":[{"name":"helical organising","type":"concept"},{"name":"trajectory plasticity","type":"concept"}],"domain_tags":["formation","demand_architecture"],"open_questions":["How do funders evaluate helical progress?","What governance structures support helical organising?"],"confidence_assessment":{"level":3,"basis":"analogy"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '5 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000003', 'assumption_background', 'Civilization is Relational Infrastructure', 'From In Defense of Civilization.', 'promoted', 4, 'observation', ARRAY['formation'], '{"title":"Civilization is Relational Infrastructure","summary":"Civilization is the shift from treating the individual as the self-sufficient unit to treating relationship as the primary unit. Freedoms are co-produced through shared constraints, infrastructures, and risk.","structured_claim":null,"assumption_type":"background","entities":[{"name":"relational infrastructure","type":"concept"},{"name":"civil relation","type":"concept"}],"domain_tags":["formation"],"open_questions":["How do we measure the health of relational infrastructure?"],"confidence_assessment":{"level":4,"basis":"observation"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '5 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000004', 'assumption_foreground', 'Predictive Capture Forecloses Trajectory Plasticity', 'From The Right to Remain Unfinalised.', 'promoted', 3, 'observation', ARRAY['formation', 'demand_architecture'], '{"title":"Predictive Capture Forecloses Trajectory Plasticity","summary":"Free agency is trajectory plasticity: the capacity to revise identity and shift commitments. Predictive capture through asymmetric sensing turns the lived present into profiles that pre-allocate your future.","structured_claim":{"if":"asymmetric sensing and predictive inference are applied without safeguards","then":"trajectory plasticity is destroyed and futures are pre-allocated","because":"predictive capture turns lived experience into profiles that foreclose the capacity to become otherwise"},"assumption_type":"foreground","entities":[{"name":"predictive capture","type":"concept"},{"name":"trajectory plasticity","type":"concept"},{"name":"right to remain unfinalised","type":"concept"}],"domain_tags":["formation","demand_architecture"],"open_questions":["What institutional forms protect the right to remain unfinalised?","How do civic registries avoid becoming tools of predictive capture?"],"confidence_assessment":{"level":3,"basis":"observation"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '4 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000005', 'learning', 'Portfolio Logic Expands Ecosystem Optionality', 'From Engineering Futures: Three Shifts.', 'promoted', 4, 'early_evidence', ARRAY['capital_strategy', 'formation'], '{"title":"Portfolio Logic Expands Ecosystem Optionality","summary":"Traditional engineering imagines the future as a destination on a critical path. Portfolio logic runs multiple experiments across varied time horizons with staged bets whose feedback loops re-inform the portfolio.","structured_claim":{"if":"transition programmes adopt portfolio logic instead of project logic","then":"ecosystem optionality expands through diverse experiments and feedback loops","because":"portfolio approaches tolerate failure in individual bets while the ensemble increases viable futures"},"assumption_type":null,"entities":[{"name":"portfolio logic","type":"concept"},{"name":"venture studio","type":"concept"}],"domain_tags":["capital_strategy","formation"],"open_questions":["How do we measure ecosystem optionality expansion?"],"confidence_assessment":{"level":4,"basis":"early_evidence"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '3 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000006', 'hunch', 'Rewilding Means Restoring Adaptive Complexity', 'From Rewilding Ourselves.', 'promoted', 3, 'analogy', ARRAY['natural_assets', 'formation'], '{"title":"Rewilding as Restoring Adaptive Complexity","summary":"Rewilding means restoring adaptive complexity where systems have been simplified for control or yield. It includes protecting irreducibility: slow trust, non-transactional relationship, unharvested attention.","structured_claim":{"if":"institutions deliberately protect irreducible complexity and restore adaptive diversity","then":"systems regain capacity for self-correction and emergent response","because":"simplification for control destroys the exploratory movement and relational diversity that makes adaptation possible"},"assumption_type":"foreground","entities":[{"name":"rewilding","type":"concept"},{"name":"irreducibility","type":"concept"},{"name":"adaptive complexity","type":"concept"}],"domain_tags":["natural_assets","formation"],"open_questions":["Where is the line between productive complexity and paralysing chaos?","How do you rewild institutions without losing accountability?"],"confidence_assessment":{"level":3,"basis":"analogy"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '2 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000007', 'person', 'Indy Johar', 'Co-founder of Dark Matter Labs.', 'promoted', 5, 'strong_evidence', ARRAY['formation'], '{"title":"Indy Johar","summary":"Co-founder of Dark Matter Labs, architect and systems thinker. Develops frameworks for institutional innovation including ex-stitutions, outcome accelerators, and the Civilization Options Fund.","structured_claim":null,"assumption_type":null,"entities":[{"name":"Indy Johar","type":"person"},{"name":"Dark Matter Labs","type":"organisation"}],"domain_tags":["formation"],"open_questions":[],"confidence_assessment":{"level":5,"basis":"strong_evidence"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '7 days');

INSERT INTO nodes (id, node_type, title, description, status, confidence_level, confidence_basis, domain_tags, llm_extraction, created_at) VALUES
('a0000001-0001-4000-8000-000000000008', 'organisation', 'Dark Matter Labs', 'A field laboratory for institutional innovation.', 'promoted', 5, 'strong_evidence', ARRAY['formation', 'capital_strategy'], '{"title":"Dark Matter Labs","summary":"A field laboratory redesigning institutional infrastructure for civilisational transition. Works on outcome accelerators, ex-stitutions, self-sovereign land, civic registries, and the Civilization Options Fund.","structured_claim":null,"assumption_type":null,"entities":[{"name":"Dark Matter Labs","type":"organisation"},{"name":"Madrid","type":"site"},{"name":"Helsinki","type":"site"},{"name":"Copenhagen","type":"site"}],"domain_tags":["formation","capital_strategy"],"open_questions":[],"confidence_assessment":{"level":5,"basis":"strong_evidence"},"suggested_connections":[]}'::jsonb, NOW() - INTERVAL '7 days');

INSERT INTO edges (source_id, target_id, edge_type, weight) VALUES
('a0000001-0001-4000-8000-000000000001', 'a0000001-0001-4000-8000-000000000002', 'supports', 1.0),
('a0000001-0001-4000-8000-000000000001', 'a0000001-0001-4000-8000-000000000003', 'requires', 1.0),
('a0000001-0001-4000-8000-000000000004', 'a0000001-0001-4000-8000-000000000001', 'contradicts', 1.0),
('a0000001-0001-4000-8000-000000000004', 'a0000001-0001-4000-8000-000000000003', 'challenges', 1.0),
('a0000001-0001-4000-8000-000000000005', 'a0000001-0001-4000-8000-000000000002', 'evolved_from', 1.0),
('a0000001-0001-4000-8000-000000000005', 'a0000001-0001-4000-8000-000000000001', 'supports', 1.0),
('a0000001-0001-4000-8000-000000000006', 'a0000001-0001-4000-8000-000000000003', 'supports', 1.0),
('a0000001-0001-4000-8000-000000000006', 'a0000001-0001-4000-8000-000000000001', 'requires', 1.0),
('a0000001-0001-4000-8000-000000000006', 'a0000001-0001-4000-8000-000000000004', 'contradicts', 1.0),
('a0000001-0001-4000-8000-000000000007', 'a0000001-0001-4000-8000-000000000008', 'works_at', 1.0),
('a0000001-0001-4000-8000-000000000001', 'a0000001-0001-4000-8000-000000000007', 'authored_by', 1.0),
('a0000001-0001-4000-8000-000000000008', 'a0000001-0001-4000-8000-000000000005', 'supports', 1.0);
